/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LibrariesLibraryIdRouteImport } from './routes/libraries/$libraryId'
import { Route as ExploreServersRouteImport } from './routes/explore/servers'
import { Route as DocsWebUiRouteImport } from './routes/docs/web-ui'
import { Route as DocsSubmitRouteImport } from './routes/docs/submit'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminLibrariesRouteImport } from './routes/admin/libraries'
import { Route as DocsMcpToolsIndexRouteImport } from './routes/docs/mcp-tools/index'
import { Route as DocsApiIndexRouteImport } from './routes/docs/api/index'
import { Route as ExploreServersServerIdRouteImport } from './routes/explore/servers.$serverId'
import { Route as DocsMcpToolsResolveLibraryRouteImport } from './routes/docs/mcp-tools/resolve-library'
import { Route as DocsMcpToolsQueryDocsRouteImport } from './routes/docs/mcp-tools/query-docs'
import { Route as DocsMcpToolsListLibrariesRouteImport } from './routes/docs/mcp-tools/list-libraries'
import { Route as DocsMcpToolsGetLibraryInfoRouteImport } from './routes/docs/mcp-tools/get-library-info'
import { Route as DocsApiSubmissionsRouteImport } from './routes/docs/api/submissions'
import { Route as DocsApiStatsRouteImport } from './routes/docs/api/stats'
import { Route as DocsApiLibrariesRouteImport } from './routes/docs/api/libraries'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdRoute = LibrariesLibraryIdRouteImport.update({
  id: '/libraries/$libraryId',
  path: '/libraries/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreServersRoute = ExploreServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => ExploreRoute,
} as any)
const DocsWebUiRoute = DocsWebUiRouteImport.update({
  id: '/docs/web-ui',
  path: '/docs/web-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSubmitRoute = DocsSubmitRouteImport.update({
  id: '/docs/submit',
  path: '/docs/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/docs/getting-started',
  path: '/docs/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLibrariesRoute = AdminLibrariesRouteImport.update({
  id: '/admin/libraries',
  path: '/admin/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMcpToolsIndexRoute = DocsMcpToolsIndexRouteImport.update({
  id: '/docs/mcp-tools/',
  path: '/docs/mcp-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiIndexRoute = DocsApiIndexRouteImport.update({
  id: '/docs/api/',
  path: '/docs/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreServersServerIdRoute = ExploreServersServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => ExploreServersRoute,
} as any)
const DocsMcpToolsResolveLibraryRoute =
  DocsMcpToolsResolveLibraryRouteImport.update({
    id: '/docs/mcp-tools/resolve-library',
    path: '/docs/mcp-tools/resolve-library',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsMcpToolsQueryDocsRoute = DocsMcpToolsQueryDocsRouteImport.update({
  id: '/docs/mcp-tools/query-docs',
  path: '/docs/mcp-tools/query-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMcpToolsListLibrariesRoute =
  DocsMcpToolsListLibrariesRouteImport.update({
    id: '/docs/mcp-tools/list-libraries',
    path: '/docs/mcp-tools/list-libraries',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsMcpToolsGetLibraryInfoRoute =
  DocsMcpToolsGetLibraryInfoRouteImport.update({
    id: '/docs/mcp-tools/get-library-info',
    path: '/docs/mcp-tools/get-library-info',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsApiSubmissionsRoute = DocsApiSubmissionsRouteImport.update({
  id: '/docs/api/submissions',
  path: '/docs/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiStatsRoute = DocsApiStatsRouteImport.update({
  id: '/docs/api/stats',
  path: '/docs/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiLibrariesRoute = DocsApiLibrariesRouteImport.update({
  id: '/docs/api/libraries',
  path: '/docs/api/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/admin/libraries': typeof AdminLibrariesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/submit': typeof DocsSubmitRoute
  '/docs/web-ui': typeof DocsWebUiRoute
  '/explore/servers': typeof ExploreServersRouteWithChildren
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/api/libraries': typeof DocsApiLibrariesRoute
  '/docs/api/stats': typeof DocsApiStatsRoute
  '/docs/api/submissions': typeof DocsApiSubmissionsRoute
  '/docs/mcp-tools/get-library-info': typeof DocsMcpToolsGetLibraryInfoRoute
  '/docs/mcp-tools/list-libraries': typeof DocsMcpToolsListLibrariesRoute
  '/docs/mcp-tools/query-docs': typeof DocsMcpToolsQueryDocsRoute
  '/docs/mcp-tools/resolve-library': typeof DocsMcpToolsResolveLibraryRoute
  '/explore/servers/$serverId': typeof ExploreServersServerIdRoute
  '/docs/api/': typeof DocsApiIndexRoute
  '/docs/mcp-tools/': typeof DocsMcpToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/admin/libraries': typeof AdminLibrariesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/submit': typeof DocsSubmitRoute
  '/docs/web-ui': typeof DocsWebUiRoute
  '/explore/servers': typeof ExploreServersRouteWithChildren
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/api/libraries': typeof DocsApiLibrariesRoute
  '/docs/api/stats': typeof DocsApiStatsRoute
  '/docs/api/submissions': typeof DocsApiSubmissionsRoute
  '/docs/mcp-tools/get-library-info': typeof DocsMcpToolsGetLibraryInfoRoute
  '/docs/mcp-tools/list-libraries': typeof DocsMcpToolsListLibrariesRoute
  '/docs/mcp-tools/query-docs': typeof DocsMcpToolsQueryDocsRoute
  '/docs/mcp-tools/resolve-library': typeof DocsMcpToolsResolveLibraryRoute
  '/explore/servers/$serverId': typeof ExploreServersServerIdRoute
  '/docs/api': typeof DocsApiIndexRoute
  '/docs/mcp-tools': typeof DocsMcpToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/submit': typeof SubmitRoute
  '/admin/libraries': typeof AdminLibrariesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/submit': typeof DocsSubmitRoute
  '/docs/web-ui': typeof DocsWebUiRoute
  '/explore/servers': typeof ExploreServersRouteWithChildren
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/api/libraries': typeof DocsApiLibrariesRoute
  '/docs/api/stats': typeof DocsApiStatsRoute
  '/docs/api/submissions': typeof DocsApiSubmissionsRoute
  '/docs/mcp-tools/get-library-info': typeof DocsMcpToolsGetLibraryInfoRoute
  '/docs/mcp-tools/list-libraries': typeof DocsMcpToolsListLibrariesRoute
  '/docs/mcp-tools/query-docs': typeof DocsMcpToolsQueryDocsRoute
  '/docs/mcp-tools/resolve-library': typeof DocsMcpToolsResolveLibraryRoute
  '/explore/servers/$serverId': typeof ExploreServersServerIdRoute
  '/docs/api/': typeof DocsApiIndexRoute
  '/docs/mcp-tools/': typeof DocsMcpToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/sign-in'
    | '/submit'
    | '/admin/libraries'
    | '/admin/submissions'
    | '/docs/getting-started'
    | '/docs/submit'
    | '/docs/web-ui'
    | '/explore/servers'
    | '/libraries/$libraryId'
    | '/admin/'
    | '/docs/'
    | '/api/auth/$'
    | '/docs/api/libraries'
    | '/docs/api/stats'
    | '/docs/api/submissions'
    | '/docs/mcp-tools/get-library-info'
    | '/docs/mcp-tools/list-libraries'
    | '/docs/mcp-tools/query-docs'
    | '/docs/mcp-tools/resolve-library'
    | '/explore/servers/$serverId'
    | '/docs/api/'
    | '/docs/mcp-tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/sign-in'
    | '/submit'
    | '/admin/libraries'
    | '/admin/submissions'
    | '/docs/getting-started'
    | '/docs/submit'
    | '/docs/web-ui'
    | '/explore/servers'
    | '/libraries/$libraryId'
    | '/admin'
    | '/docs'
    | '/api/auth/$'
    | '/docs/api/libraries'
    | '/docs/api/stats'
    | '/docs/api/submissions'
    | '/docs/mcp-tools/get-library-info'
    | '/docs/mcp-tools/list-libraries'
    | '/docs/mcp-tools/query-docs'
    | '/docs/mcp-tools/resolve-library'
    | '/explore/servers/$serverId'
    | '/docs/api'
    | '/docs/mcp-tools'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/sign-in'
    | '/submit'
    | '/admin/libraries'
    | '/admin/submissions'
    | '/docs/getting-started'
    | '/docs/submit'
    | '/docs/web-ui'
    | '/explore/servers'
    | '/libraries/$libraryId'
    | '/admin/'
    | '/docs/'
    | '/api/auth/$'
    | '/docs/api/libraries'
    | '/docs/api/stats'
    | '/docs/api/submissions'
    | '/docs/mcp-tools/get-library-info'
    | '/docs/mcp-tools/list-libraries'
    | '/docs/mcp-tools/query-docs'
    | '/docs/mcp-tools/resolve-library'
    | '/explore/servers/$serverId'
    | '/docs/api/'
    | '/docs/mcp-tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  SignInRoute: typeof SignInRoute
  SubmitRoute: typeof SubmitRoute
  AdminLibrariesRoute: typeof AdminLibrariesRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsSubmitRoute: typeof DocsSubmitRoute
  DocsWebUiRoute: typeof DocsWebUiRoute
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DocsApiLibrariesRoute: typeof DocsApiLibrariesRoute
  DocsApiStatsRoute: typeof DocsApiStatsRoute
  DocsApiSubmissionsRoute: typeof DocsApiSubmissionsRoute
  DocsMcpToolsGetLibraryInfoRoute: typeof DocsMcpToolsGetLibraryInfoRoute
  DocsMcpToolsListLibrariesRoute: typeof DocsMcpToolsListLibrariesRoute
  DocsMcpToolsQueryDocsRoute: typeof DocsMcpToolsQueryDocsRoute
  DocsMcpToolsResolveLibraryRoute: typeof DocsMcpToolsResolveLibraryRoute
  DocsApiIndexRoute: typeof DocsApiIndexRoute
  DocsMcpToolsIndexRoute: typeof DocsMcpToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId': {
      id: '/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/servers': {
      id: '/explore/servers'
      path: '/servers'
      fullPath: '/explore/servers'
      preLoaderRoute: typeof ExploreServersRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/docs/web-ui': {
      id: '/docs/web-ui'
      path: '/docs/web-ui'
      fullPath: '/docs/web-ui'
      preLoaderRoute: typeof DocsWebUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/submit': {
      id: '/docs/submit'
      path: '/docs/submit'
      fullPath: '/docs/submit'
      preLoaderRoute: typeof DocsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/libraries': {
      id: '/admin/libraries'
      path: '/admin/libraries'
      fullPath: '/admin/libraries'
      preLoaderRoute: typeof AdminLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp-tools/': {
      id: '/docs/mcp-tools/'
      path: '/docs/mcp-tools'
      fullPath: '/docs/mcp-tools/'
      preLoaderRoute: typeof DocsMcpToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/': {
      id: '/docs/api/'
      path: '/docs/api'
      fullPath: '/docs/api/'
      preLoaderRoute: typeof DocsApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/servers/$serverId': {
      id: '/explore/servers/$serverId'
      path: '/$serverId'
      fullPath: '/explore/servers/$serverId'
      preLoaderRoute: typeof ExploreServersServerIdRouteImport
      parentRoute: typeof ExploreServersRoute
    }
    '/docs/mcp-tools/resolve-library': {
      id: '/docs/mcp-tools/resolve-library'
      path: '/docs/mcp-tools/resolve-library'
      fullPath: '/docs/mcp-tools/resolve-library'
      preLoaderRoute: typeof DocsMcpToolsResolveLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp-tools/query-docs': {
      id: '/docs/mcp-tools/query-docs'
      path: '/docs/mcp-tools/query-docs'
      fullPath: '/docs/mcp-tools/query-docs'
      preLoaderRoute: typeof DocsMcpToolsQueryDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp-tools/list-libraries': {
      id: '/docs/mcp-tools/list-libraries'
      path: '/docs/mcp-tools/list-libraries'
      fullPath: '/docs/mcp-tools/list-libraries'
      preLoaderRoute: typeof DocsMcpToolsListLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp-tools/get-library-info': {
      id: '/docs/mcp-tools/get-library-info'
      path: '/docs/mcp-tools/get-library-info'
      fullPath: '/docs/mcp-tools/get-library-info'
      preLoaderRoute: typeof DocsMcpToolsGetLibraryInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/submissions': {
      id: '/docs/api/submissions'
      path: '/docs/api/submissions'
      fullPath: '/docs/api/submissions'
      preLoaderRoute: typeof DocsApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/stats': {
      id: '/docs/api/stats'
      path: '/docs/api/stats'
      fullPath: '/docs/api/stats'
      preLoaderRoute: typeof DocsApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/libraries': {
      id: '/docs/api/libraries'
      path: '/docs/api/libraries'
      fullPath: '/docs/api/libraries'
      preLoaderRoute: typeof DocsApiLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExploreServersRouteChildren {
  ExploreServersServerIdRoute: typeof ExploreServersServerIdRoute
}

const ExploreServersRouteChildren: ExploreServersRouteChildren = {
  ExploreServersServerIdRoute: ExploreServersServerIdRoute,
}

const ExploreServersRouteWithChildren = ExploreServersRoute._addFileChildren(
  ExploreServersRouteChildren,
)

interface ExploreRouteChildren {
  ExploreServersRoute: typeof ExploreServersRouteWithChildren
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreServersRoute: ExploreServersRouteWithChildren,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRouteWithChildren,
  SignInRoute: SignInRoute,
  SubmitRoute: SubmitRoute,
  AdminLibrariesRoute: AdminLibrariesRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsSubmitRoute: DocsSubmitRoute,
  DocsWebUiRoute: DocsWebUiRoute,
  LibrariesLibraryIdRoute: LibrariesLibraryIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DocsApiLibrariesRoute: DocsApiLibrariesRoute,
  DocsApiStatsRoute: DocsApiStatsRoute,
  DocsApiSubmissionsRoute: DocsApiSubmissionsRoute,
  DocsMcpToolsGetLibraryInfoRoute: DocsMcpToolsGetLibraryInfoRoute,
  DocsMcpToolsListLibrariesRoute: DocsMcpToolsListLibrariesRoute,
  DocsMcpToolsQueryDocsRoute: DocsMcpToolsQueryDocsRoute,
  DocsMcpToolsResolveLibraryRoute: DocsMcpToolsResolveLibraryRoute,
  DocsApiIndexRoute: DocsApiIndexRoute,
  DocsMcpToolsIndexRoute: DocsMcpToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
