/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TerminalRouteImport } from "./routes/terminal";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as PlansRouteImport } from "./routes/plans";
import { Route as ExploreRouteImport } from "./routes/explore";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ExploreIndexRouteImport } from "./routes/explore/index";
import { Route as CodeIndexRouteImport } from "./routes/code/index";
import { Route as LibrariesLibraryIdRouteImport } from "./routes/libraries/$libraryId";
import { Route as ExploreStatsRouteImport } from "./routes/explore/stats";
import { Route as ExploreDocsRouteImport } from "./routes/explore/docs";
import { Route as CodeSessionsRouteImport } from "./routes/code/sessions";
import { Route as AuthCliRouteImport } from "./routes/auth/cli";
import { Route as AuthedSubmitServerRouteImport } from "./routes/_authed/submit-server";
import { Route as AuthedSubmitRouteImport } from "./routes/_authed/submit";
import { Route as AuthedDashboardRouteImport } from "./routes/_authed/dashboard";
import { Route as AuthedAdminRouteImport } from "./routes/_authed/admin";
import { Route as ExploreSkillsIndexRouteImport } from "./routes/explore/skills.index";
import { Route as ExploreServersIndexRouteImport } from "./routes/explore/servers.index";
import { Route as AuthedSettingsIndexRouteImport } from "./routes/_authed/settings/index";
import { Route as AuthedDashboardIndexRouteImport } from "./routes/_authed/dashboard/index";
import { Route as AuthedAdminIndexRouteImport } from "./routes/_authed/admin/index";
import { Route as ExploreStacksStackSlugRouteImport } from "./routes/explore/stacks.$stackSlug";
import { Route as ExploreSkillsSkillIdRouteImport } from "./routes/explore/skills.$skillId";
import { Route as ExploreServersServerIdRouteImport } from "./routes/explore/servers.$serverId";
import { Route as ExploreDocsLibraryIdRouteImport } from "./routes/explore/docs.$libraryId";
import { Route as CodeSessionSessionIdRouteImport } from "./routes/code/session.$sessionId";
import { Route as AuthedSettingsSecretsRouteImport } from "./routes/_authed/settings/secrets";
import { Route as AuthedDashboardSkillsRouteImport } from "./routes/_authed/dashboard/skills";
import { Route as AuthedDashboardReposRouteImport } from "./routes/_authed/dashboard/repos";
import { Route as AuthedDashboardKeysRouteImport } from "./routes/_authed/dashboard/keys";
import { Route as AuthedDashboardBrainRouteImport } from "./routes/_authed/dashboard/brain";
import { Route as AuthedDashboardBillingRouteImport } from "./routes/_authed/dashboard/billing";
import { Route as AuthedAdminSubmissionsRouteImport } from "./routes/_authed/admin/submissions";
import { Route as AuthedAdminServerSubmissionsRouteImport } from "./routes/_authed/admin/server-submissions";
import { Route as AuthedAdminLibrariesRouteImport } from "./routes/_authed/admin/libraries";
import { Route as AuthedDashboardStacksIndexRouteImport } from "./routes/_authed/dashboard/stacks.index";
import { Route as AuthedDashboardPromptsIndexRouteImport } from "./routes/_authed/dashboard/prompts.index";
import { Route as AuthedDashboardStacksNewRouteImport } from "./routes/_authed/dashboard/stacks.new";
import { Route as AuthedDashboardStacksStackIdRouteImport } from "./routes/_authed/dashboard/stacks.$stackId";
import { Route as AuthedDashboardPromptsNewRouteImport } from "./routes/_authed/dashboard/prompts.new";
import { Route as AuthedDashboardPromptsPromptIdRouteImport } from "./routes/_authed/dashboard/prompts.$promptId";

const TerminalRoute = TerminalRouteImport.update({
  id: "/terminal",
  path: "/terminal",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const PlansRoute = PlansRouteImport.update({
  id: "/plans",
  path: "/plans",
  getParentRoute: () => rootRouteImport,
} as any);
const ExploreRoute = ExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ExploreRoute,
} as any);
const CodeIndexRoute = CodeIndexRouteImport.update({
  id: "/code/",
  path: "/code/",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/code/index.lazy").then((d) => d.Route));
const LibrariesLibraryIdRoute = LibrariesLibraryIdRouteImport.update({
  id: "/libraries/$libraryId",
  path: "/libraries/$libraryId",
  getParentRoute: () => rootRouteImport,
} as any);
const ExploreStatsRoute = ExploreStatsRouteImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => ExploreRoute,
} as any);
const ExploreDocsRoute = ExploreDocsRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => ExploreRoute,
} as any);
const CodeSessionsRoute = CodeSessionsRouteImport.update({
  id: "/code/sessions",
  path: "/code/sessions",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/code/sessions.lazy").then((d) => d.Route));
const AuthCliRoute = AuthCliRouteImport.update({
  id: "/auth/cli",
  path: "/auth/cli",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedSubmitServerRoute = AuthedSubmitServerRouteImport.update({
  id: "/submit-server",
  path: "/submit-server",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedSubmitRoute = AuthedSubmitRouteImport.update({
  id: "/submit",
  path: "/submit",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthedRoute,
} as any);
const ExploreSkillsIndexRoute = ExploreSkillsIndexRouteImport.update({
  id: "/skills/",
  path: "/skills/",
  getParentRoute: () => ExploreRoute,
} as any);
const ExploreServersIndexRoute = ExploreServersIndexRouteImport.update({
  id: "/servers/",
  path: "/servers/",
  getParentRoute: () => ExploreRoute,
} as any);
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedAdminRoute,
} as any);
const ExploreStacksStackSlugRoute = ExploreStacksStackSlugRouteImport.update({
  id: "/stacks/$stackSlug",
  path: "/stacks/$stackSlug",
  getParentRoute: () => ExploreRoute,
} as any);
const ExploreSkillsSkillIdRoute = ExploreSkillsSkillIdRouteImport.update({
  id: "/skills/$skillId",
  path: "/skills/$skillId",
  getParentRoute: () => ExploreRoute,
} as any);
const ExploreServersServerIdRoute = ExploreServersServerIdRouteImport.update({
  id: "/servers/$serverId",
  path: "/servers/$serverId",
  getParentRoute: () => ExploreRoute,
} as any);
const ExploreDocsLibraryIdRoute = ExploreDocsLibraryIdRouteImport.update({
  id: "/$libraryId",
  path: "/$libraryId",
  getParentRoute: () => ExploreDocsRoute,
} as any);
const CodeSessionSessionIdRoute = CodeSessionSessionIdRouteImport.update({
  id: "/code/session/$sessionId",
  path: "/code/session/$sessionId",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/code/session.$sessionId.lazy").then((d) => d.Route));
const AuthedSettingsSecretsRoute = AuthedSettingsSecretsRouteImport.update({
  id: "/settings/secrets",
  path: "/settings/secrets",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedDashboardSkillsRoute = AuthedDashboardSkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardReposRoute = AuthedDashboardReposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardKeysRoute = AuthedDashboardKeysRouteImport.update({
  id: "/keys",
  path: "/keys",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardBrainRoute = AuthedDashboardBrainRouteImport.update({
  id: "/brain",
  path: "/brain",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardBillingRoute = AuthedDashboardBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedAdminSubmissionsRoute = AuthedAdminSubmissionsRouteImport.update({
  id: "/submissions",
  path: "/submissions",
  getParentRoute: () => AuthedAdminRoute,
} as any);
const AuthedAdminServerSubmissionsRoute = AuthedAdminServerSubmissionsRouteImport.update({
  id: "/server-submissions",
  path: "/server-submissions",
  getParentRoute: () => AuthedAdminRoute,
} as any);
const AuthedAdminLibrariesRoute = AuthedAdminLibrariesRouteImport.update({
  id: "/libraries",
  path: "/libraries",
  getParentRoute: () => AuthedAdminRoute,
} as any);
const AuthedDashboardStacksIndexRoute = AuthedDashboardStacksIndexRouteImport.update({
  id: "/stacks/",
  path: "/stacks/",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardPromptsIndexRoute = AuthedDashboardPromptsIndexRouteImport.update({
  id: "/prompts/",
  path: "/prompts/",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardStacksNewRoute = AuthedDashboardStacksNewRouteImport.update({
  id: "/stacks/new",
  path: "/stacks/new",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardStacksStackIdRoute = AuthedDashboardStacksStackIdRouteImport.update({
  id: "/stacks/$stackId",
  path: "/stacks/$stackId",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardPromptsNewRoute = AuthedDashboardPromptsNewRouteImport.update({
  id: "/prompts/new",
  path: "/prompts/new",
  getParentRoute: () => AuthedDashboardRoute,
} as any);
const AuthedDashboardPromptsPromptIdRoute = AuthedDashboardPromptsPromptIdRouteImport.update({
  id: "/prompts/$promptId",
  path: "/prompts/$promptId",
  getParentRoute: () => AuthedDashboardRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/explore": typeof ExploreRouteWithChildren;
  "/plans": typeof PlansRoute;
  "/sign-in": typeof SignInRoute;
  "/terminal": typeof TerminalRoute;
  "/admin": typeof AuthedAdminRouteWithChildren;
  "/dashboard": typeof AuthedDashboardRouteWithChildren;
  "/submit": typeof AuthedSubmitRoute;
  "/submit-server": typeof AuthedSubmitServerRoute;
  "/auth/cli": typeof AuthCliRoute;
  "/code/sessions": typeof CodeSessionsRoute;
  "/explore/docs": typeof ExploreDocsRouteWithChildren;
  "/explore/stats": typeof ExploreStatsRoute;
  "/libraries/$libraryId": typeof LibrariesLibraryIdRoute;
  "/code/": typeof CodeIndexRoute;
  "/explore/": typeof ExploreIndexRoute;
  "/admin/libraries": typeof AuthedAdminLibrariesRoute;
  "/admin/server-submissions": typeof AuthedAdminServerSubmissionsRoute;
  "/admin/submissions": typeof AuthedAdminSubmissionsRoute;
  "/dashboard/billing": typeof AuthedDashboardBillingRoute;
  "/dashboard/brain": typeof AuthedDashboardBrainRoute;
  "/dashboard/keys": typeof AuthedDashboardKeysRoute;
  "/dashboard/repos": typeof AuthedDashboardReposRoute;
  "/dashboard/skills": typeof AuthedDashboardSkillsRoute;
  "/settings/secrets": typeof AuthedSettingsSecretsRoute;
  "/code/session/$sessionId": typeof CodeSessionSessionIdRoute;
  "/explore/docs/$libraryId": typeof ExploreDocsLibraryIdRoute;
  "/explore/servers/$serverId": typeof ExploreServersServerIdRoute;
  "/explore/skills/$skillId": typeof ExploreSkillsSkillIdRoute;
  "/explore/stacks/$stackSlug": typeof ExploreStacksStackSlugRoute;
  "/admin/": typeof AuthedAdminIndexRoute;
  "/dashboard/": typeof AuthedDashboardIndexRoute;
  "/settings/": typeof AuthedSettingsIndexRoute;
  "/explore/servers/": typeof ExploreServersIndexRoute;
  "/explore/skills/": typeof ExploreSkillsIndexRoute;
  "/dashboard/prompts/$promptId": typeof AuthedDashboardPromptsPromptIdRoute;
  "/dashboard/prompts/new": typeof AuthedDashboardPromptsNewRoute;
  "/dashboard/stacks/$stackId": typeof AuthedDashboardStacksStackIdRoute;
  "/dashboard/stacks/new": typeof AuthedDashboardStacksNewRoute;
  "/dashboard/prompts/": typeof AuthedDashboardPromptsIndexRoute;
  "/dashboard/stacks/": typeof AuthedDashboardStacksIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/plans": typeof PlansRoute;
  "/sign-in": typeof SignInRoute;
  "/terminal": typeof TerminalRoute;
  "/submit": typeof AuthedSubmitRoute;
  "/submit-server": typeof AuthedSubmitServerRoute;
  "/auth/cli": typeof AuthCliRoute;
  "/code/sessions": typeof CodeSessionsRoute;
  "/explore/docs": typeof ExploreDocsRouteWithChildren;
  "/explore/stats": typeof ExploreStatsRoute;
  "/libraries/$libraryId": typeof LibrariesLibraryIdRoute;
  "/code": typeof CodeIndexRoute;
  "/explore": typeof ExploreIndexRoute;
  "/admin/libraries": typeof AuthedAdminLibrariesRoute;
  "/admin/server-submissions": typeof AuthedAdminServerSubmissionsRoute;
  "/admin/submissions": typeof AuthedAdminSubmissionsRoute;
  "/dashboard/billing": typeof AuthedDashboardBillingRoute;
  "/dashboard/brain": typeof AuthedDashboardBrainRoute;
  "/dashboard/keys": typeof AuthedDashboardKeysRoute;
  "/dashboard/repos": typeof AuthedDashboardReposRoute;
  "/dashboard/skills": typeof AuthedDashboardSkillsRoute;
  "/settings/secrets": typeof AuthedSettingsSecretsRoute;
  "/code/session/$sessionId": typeof CodeSessionSessionIdRoute;
  "/explore/docs/$libraryId": typeof ExploreDocsLibraryIdRoute;
  "/explore/servers/$serverId": typeof ExploreServersServerIdRoute;
  "/explore/skills/$skillId": typeof ExploreSkillsSkillIdRoute;
  "/explore/stacks/$stackSlug": typeof ExploreStacksStackSlugRoute;
  "/admin": typeof AuthedAdminIndexRoute;
  "/dashboard": typeof AuthedDashboardIndexRoute;
  "/settings": typeof AuthedSettingsIndexRoute;
  "/explore/servers": typeof ExploreServersIndexRoute;
  "/explore/skills": typeof ExploreSkillsIndexRoute;
  "/dashboard/prompts/$promptId": typeof AuthedDashboardPromptsPromptIdRoute;
  "/dashboard/prompts/new": typeof AuthedDashboardPromptsNewRoute;
  "/dashboard/stacks/$stackId": typeof AuthedDashboardStacksStackIdRoute;
  "/dashboard/stacks/new": typeof AuthedDashboardStacksNewRoute;
  "/dashboard/prompts": typeof AuthedDashboardPromptsIndexRoute;
  "/dashboard/stacks": typeof AuthedDashboardStacksIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/explore": typeof ExploreRouteWithChildren;
  "/plans": typeof PlansRoute;
  "/sign-in": typeof SignInRoute;
  "/terminal": typeof TerminalRoute;
  "/_authed/admin": typeof AuthedAdminRouteWithChildren;
  "/_authed/dashboard": typeof AuthedDashboardRouteWithChildren;
  "/_authed/submit": typeof AuthedSubmitRoute;
  "/_authed/submit-server": typeof AuthedSubmitServerRoute;
  "/auth/cli": typeof AuthCliRoute;
  "/code/sessions": typeof CodeSessionsRoute;
  "/explore/docs": typeof ExploreDocsRouteWithChildren;
  "/explore/stats": typeof ExploreStatsRoute;
  "/libraries/$libraryId": typeof LibrariesLibraryIdRoute;
  "/code/": typeof CodeIndexRoute;
  "/explore/": typeof ExploreIndexRoute;
  "/_authed/admin/libraries": typeof AuthedAdminLibrariesRoute;
  "/_authed/admin/server-submissions": typeof AuthedAdminServerSubmissionsRoute;
  "/_authed/admin/submissions": typeof AuthedAdminSubmissionsRoute;
  "/_authed/dashboard/billing": typeof AuthedDashboardBillingRoute;
  "/_authed/dashboard/brain": typeof AuthedDashboardBrainRoute;
  "/_authed/dashboard/keys": typeof AuthedDashboardKeysRoute;
  "/_authed/dashboard/repos": typeof AuthedDashboardReposRoute;
  "/_authed/dashboard/skills": typeof AuthedDashboardSkillsRoute;
  "/_authed/settings/secrets": typeof AuthedSettingsSecretsRoute;
  "/code/session/$sessionId": typeof CodeSessionSessionIdRoute;
  "/explore/docs/$libraryId": typeof ExploreDocsLibraryIdRoute;
  "/explore/servers/$serverId": typeof ExploreServersServerIdRoute;
  "/explore/skills/$skillId": typeof ExploreSkillsSkillIdRoute;
  "/explore/stacks/$stackSlug": typeof ExploreStacksStackSlugRoute;
  "/_authed/admin/": typeof AuthedAdminIndexRoute;
  "/_authed/dashboard/": typeof AuthedDashboardIndexRoute;
  "/_authed/settings/": typeof AuthedSettingsIndexRoute;
  "/explore/servers/": typeof ExploreServersIndexRoute;
  "/explore/skills/": typeof ExploreSkillsIndexRoute;
  "/_authed/dashboard/prompts/$promptId": typeof AuthedDashboardPromptsPromptIdRoute;
  "/_authed/dashboard/prompts/new": typeof AuthedDashboardPromptsNewRoute;
  "/_authed/dashboard/stacks/$stackId": typeof AuthedDashboardStacksStackIdRoute;
  "/_authed/dashboard/stacks/new": typeof AuthedDashboardStacksNewRoute;
  "/_authed/dashboard/prompts/": typeof AuthedDashboardPromptsIndexRoute;
  "/_authed/dashboard/stacks/": typeof AuthedDashboardStacksIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/explore"
    | "/plans"
    | "/sign-in"
    | "/terminal"
    | "/admin"
    | "/dashboard"
    | "/submit"
    | "/submit-server"
    | "/auth/cli"
    | "/code/sessions"
    | "/explore/docs"
    | "/explore/stats"
    | "/libraries/$libraryId"
    | "/code/"
    | "/explore/"
    | "/admin/libraries"
    | "/admin/server-submissions"
    | "/admin/submissions"
    | "/dashboard/billing"
    | "/dashboard/brain"
    | "/dashboard/keys"
    | "/dashboard/repos"
    | "/dashboard/skills"
    | "/settings/secrets"
    | "/code/session/$sessionId"
    | "/explore/docs/$libraryId"
    | "/explore/servers/$serverId"
    | "/explore/skills/$skillId"
    | "/explore/stacks/$stackSlug"
    | "/admin/"
    | "/dashboard/"
    | "/settings/"
    | "/explore/servers/"
    | "/explore/skills/"
    | "/dashboard/prompts/$promptId"
    | "/dashboard/prompts/new"
    | "/dashboard/stacks/$stackId"
    | "/dashboard/stacks/new"
    | "/dashboard/prompts/"
    | "/dashboard/stacks/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/plans"
    | "/sign-in"
    | "/terminal"
    | "/submit"
    | "/submit-server"
    | "/auth/cli"
    | "/code/sessions"
    | "/explore/docs"
    | "/explore/stats"
    | "/libraries/$libraryId"
    | "/code"
    | "/explore"
    | "/admin/libraries"
    | "/admin/server-submissions"
    | "/admin/submissions"
    | "/dashboard/billing"
    | "/dashboard/brain"
    | "/dashboard/keys"
    | "/dashboard/repos"
    | "/dashboard/skills"
    | "/settings/secrets"
    | "/code/session/$sessionId"
    | "/explore/docs/$libraryId"
    | "/explore/servers/$serverId"
    | "/explore/skills/$skillId"
    | "/explore/stacks/$stackSlug"
    | "/admin"
    | "/dashboard"
    | "/settings"
    | "/explore/servers"
    | "/explore/skills"
    | "/dashboard/prompts/$promptId"
    | "/dashboard/prompts/new"
    | "/dashboard/stacks/$stackId"
    | "/dashboard/stacks/new"
    | "/dashboard/prompts"
    | "/dashboard/stacks";
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/explore"
    | "/plans"
    | "/sign-in"
    | "/terminal"
    | "/_authed/admin"
    | "/_authed/dashboard"
    | "/_authed/submit"
    | "/_authed/submit-server"
    | "/auth/cli"
    | "/code/sessions"
    | "/explore/docs"
    | "/explore/stats"
    | "/libraries/$libraryId"
    | "/code/"
    | "/explore/"
    | "/_authed/admin/libraries"
    | "/_authed/admin/server-submissions"
    | "/_authed/admin/submissions"
    | "/_authed/dashboard/billing"
    | "/_authed/dashboard/brain"
    | "/_authed/dashboard/keys"
    | "/_authed/dashboard/repos"
    | "/_authed/dashboard/skills"
    | "/_authed/settings/secrets"
    | "/code/session/$sessionId"
    | "/explore/docs/$libraryId"
    | "/explore/servers/$serverId"
    | "/explore/skills/$skillId"
    | "/explore/stacks/$stackSlug"
    | "/_authed/admin/"
    | "/_authed/dashboard/"
    | "/_authed/settings/"
    | "/explore/servers/"
    | "/explore/skills/"
    | "/_authed/dashboard/prompts/$promptId"
    | "/_authed/dashboard/prompts/new"
    | "/_authed/dashboard/stacks/$stackId"
    | "/_authed/dashboard/stacks/new"
    | "/_authed/dashboard/prompts/"
    | "/_authed/dashboard/stacks/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  ExploreRoute: typeof ExploreRouteWithChildren;
  PlansRoute: typeof PlansRoute;
  SignInRoute: typeof SignInRoute;
  TerminalRoute: typeof TerminalRoute;
  AuthCliRoute: typeof AuthCliRoute;
  CodeSessionsRoute: typeof CodeSessionsRoute;
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRoute;
  CodeIndexRoute: typeof CodeIndexRoute;
  CodeSessionSessionIdRoute: typeof CodeSessionSessionIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terminal": {
      id: "/terminal";
      path: "/terminal";
      fullPath: "/terminal";
      preLoaderRoute: typeof TerminalRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/plans": {
      id: "/plans";
      path: "/plans";
      fullPath: "/plans";
      preLoaderRoute: typeof PlansRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/explore": {
      id: "/explore";
      path: "/explore";
      fullPath: "/explore";
      preLoaderRoute: typeof ExploreRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/explore/": {
      id: "/explore/";
      path: "/";
      fullPath: "/explore/";
      preLoaderRoute: typeof ExploreIndexRouteImport;
      parentRoute: typeof ExploreRoute;
    };
    "/code/": {
      id: "/code/";
      path: "/code";
      fullPath: "/code/";
      preLoaderRoute: typeof CodeIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/libraries/$libraryId": {
      id: "/libraries/$libraryId";
      path: "/libraries/$libraryId";
      fullPath: "/libraries/$libraryId";
      preLoaderRoute: typeof LibrariesLibraryIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/explore/stats": {
      id: "/explore/stats";
      path: "/stats";
      fullPath: "/explore/stats";
      preLoaderRoute: typeof ExploreStatsRouteImport;
      parentRoute: typeof ExploreRoute;
    };
    "/explore/docs": {
      id: "/explore/docs";
      path: "/docs";
      fullPath: "/explore/docs";
      preLoaderRoute: typeof ExploreDocsRouteImport;
      parentRoute: typeof ExploreRoute;
    };
    "/code/sessions": {
      id: "/code/sessions";
      path: "/code/sessions";
      fullPath: "/code/sessions";
      preLoaderRoute: typeof CodeSessionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/cli": {
      id: "/auth/cli";
      path: "/auth/cli";
      fullPath: "/auth/cli";
      preLoaderRoute: typeof AuthCliRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/submit-server": {
      id: "/_authed/submit-server";
      path: "/submit-server";
      fullPath: "/submit-server";
      preLoaderRoute: typeof AuthedSubmitServerRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/submit": {
      id: "/_authed/submit";
      path: "/submit";
      fullPath: "/submit";
      preLoaderRoute: typeof AuthedSubmitRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/dashboard": {
      id: "/_authed/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthedDashboardRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/admin": {
      id: "/_authed/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AuthedAdminRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/explore/skills/": {
      id: "/explore/skills/";
      path: "/skills";
      fullPath: "/explore/skills/";
      preLoaderRoute: typeof ExploreSkillsIndexRouteImport;
      parentRoute: typeof ExploreRoute;
    };
    "/explore/servers/": {
      id: "/explore/servers/";
      path: "/servers";
      fullPath: "/explore/servers/";
      preLoaderRoute: typeof ExploreServersIndexRouteImport;
      parentRoute: typeof ExploreRoute;
    };
    "/_authed/settings/": {
      id: "/_authed/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/dashboard/": {
      id: "/_authed/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/admin/": {
      id: "/_authed/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AuthedAdminIndexRouteImport;
      parentRoute: typeof AuthedAdminRoute;
    };
    "/explore/stacks/$stackSlug": {
      id: "/explore/stacks/$stackSlug";
      path: "/stacks/$stackSlug";
      fullPath: "/explore/stacks/$stackSlug";
      preLoaderRoute: typeof ExploreStacksStackSlugRouteImport;
      parentRoute: typeof ExploreRoute;
    };
    "/explore/skills/$skillId": {
      id: "/explore/skills/$skillId";
      path: "/skills/$skillId";
      fullPath: "/explore/skills/$skillId";
      preLoaderRoute: typeof ExploreSkillsSkillIdRouteImport;
      parentRoute: typeof ExploreRoute;
    };
    "/explore/servers/$serverId": {
      id: "/explore/servers/$serverId";
      path: "/servers/$serverId";
      fullPath: "/explore/servers/$serverId";
      preLoaderRoute: typeof ExploreServersServerIdRouteImport;
      parentRoute: typeof ExploreRoute;
    };
    "/explore/docs/$libraryId": {
      id: "/explore/docs/$libraryId";
      path: "/$libraryId";
      fullPath: "/explore/docs/$libraryId";
      preLoaderRoute: typeof ExploreDocsLibraryIdRouteImport;
      parentRoute: typeof ExploreDocsRoute;
    };
    "/code/session/$sessionId": {
      id: "/code/session/$sessionId";
      path: "/code/session/$sessionId";
      fullPath: "/code/session/$sessionId";
      preLoaderRoute: typeof CodeSessionSessionIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/settings/secrets": {
      id: "/_authed/settings/secrets";
      path: "/settings/secrets";
      fullPath: "/settings/secrets";
      preLoaderRoute: typeof AuthedSettingsSecretsRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/dashboard/skills": {
      id: "/_authed/dashboard/skills";
      path: "/skills";
      fullPath: "/dashboard/skills";
      preLoaderRoute: typeof AuthedDashboardSkillsRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/repos": {
      id: "/_authed/dashboard/repos";
      path: "/repos";
      fullPath: "/dashboard/repos";
      preLoaderRoute: typeof AuthedDashboardReposRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/keys": {
      id: "/_authed/dashboard/keys";
      path: "/keys";
      fullPath: "/dashboard/keys";
      preLoaderRoute: typeof AuthedDashboardKeysRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/brain": {
      id: "/_authed/dashboard/brain";
      path: "/brain";
      fullPath: "/dashboard/brain";
      preLoaderRoute: typeof AuthedDashboardBrainRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/billing": {
      id: "/_authed/dashboard/billing";
      path: "/billing";
      fullPath: "/dashboard/billing";
      preLoaderRoute: typeof AuthedDashboardBillingRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/admin/submissions": {
      id: "/_authed/admin/submissions";
      path: "/submissions";
      fullPath: "/admin/submissions";
      preLoaderRoute: typeof AuthedAdminSubmissionsRouteImport;
      parentRoute: typeof AuthedAdminRoute;
    };
    "/_authed/admin/server-submissions": {
      id: "/_authed/admin/server-submissions";
      path: "/server-submissions";
      fullPath: "/admin/server-submissions";
      preLoaderRoute: typeof AuthedAdminServerSubmissionsRouteImport;
      parentRoute: typeof AuthedAdminRoute;
    };
    "/_authed/admin/libraries": {
      id: "/_authed/admin/libraries";
      path: "/libraries";
      fullPath: "/admin/libraries";
      preLoaderRoute: typeof AuthedAdminLibrariesRouteImport;
      parentRoute: typeof AuthedAdminRoute;
    };
    "/_authed/dashboard/stacks/": {
      id: "/_authed/dashboard/stacks/";
      path: "/stacks";
      fullPath: "/dashboard/stacks/";
      preLoaderRoute: typeof AuthedDashboardStacksIndexRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/prompts/": {
      id: "/_authed/dashboard/prompts/";
      path: "/prompts";
      fullPath: "/dashboard/prompts/";
      preLoaderRoute: typeof AuthedDashboardPromptsIndexRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/stacks/new": {
      id: "/_authed/dashboard/stacks/new";
      path: "/stacks/new";
      fullPath: "/dashboard/stacks/new";
      preLoaderRoute: typeof AuthedDashboardStacksNewRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/stacks/$stackId": {
      id: "/_authed/dashboard/stacks/$stackId";
      path: "/stacks/$stackId";
      fullPath: "/dashboard/stacks/$stackId";
      preLoaderRoute: typeof AuthedDashboardStacksStackIdRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/prompts/new": {
      id: "/_authed/dashboard/prompts/new";
      path: "/prompts/new";
      fullPath: "/dashboard/prompts/new";
      preLoaderRoute: typeof AuthedDashboardPromptsNewRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
    "/_authed/dashboard/prompts/$promptId": {
      id: "/_authed/dashboard/prompts/$promptId";
      path: "/prompts/$promptId";
      fullPath: "/dashboard/prompts/$promptId";
      preLoaderRoute: typeof AuthedDashboardPromptsPromptIdRouteImport;
      parentRoute: typeof AuthedDashboardRoute;
    };
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminLibrariesRoute: typeof AuthedAdminLibrariesRoute;
  AuthedAdminServerSubmissionsRoute: typeof AuthedAdminServerSubmissionsRoute;
  AuthedAdminSubmissionsRoute: typeof AuthedAdminSubmissionsRoute;
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute;
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminLibrariesRoute: AuthedAdminLibrariesRoute,
  AuthedAdminServerSubmissionsRoute: AuthedAdminServerSubmissionsRoute,
  AuthedAdminSubmissionsRoute: AuthedAdminSubmissionsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
};

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(AuthedAdminRouteChildren);

interface AuthedDashboardRouteChildren {
  AuthedDashboardBillingRoute: typeof AuthedDashboardBillingRoute;
  AuthedDashboardBrainRoute: typeof AuthedDashboardBrainRoute;
  AuthedDashboardKeysRoute: typeof AuthedDashboardKeysRoute;
  AuthedDashboardReposRoute: typeof AuthedDashboardReposRoute;
  AuthedDashboardSkillsRoute: typeof AuthedDashboardSkillsRoute;
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute;
  AuthedDashboardPromptsPromptIdRoute: typeof AuthedDashboardPromptsPromptIdRoute;
  AuthedDashboardPromptsNewRoute: typeof AuthedDashboardPromptsNewRoute;
  AuthedDashboardStacksStackIdRoute: typeof AuthedDashboardStacksStackIdRoute;
  AuthedDashboardStacksNewRoute: typeof AuthedDashboardStacksNewRoute;
  AuthedDashboardPromptsIndexRoute: typeof AuthedDashboardPromptsIndexRoute;
  AuthedDashboardStacksIndexRoute: typeof AuthedDashboardStacksIndexRoute;
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardBillingRoute: AuthedDashboardBillingRoute,
  AuthedDashboardBrainRoute: AuthedDashboardBrainRoute,
  AuthedDashboardKeysRoute: AuthedDashboardKeysRoute,
  AuthedDashboardReposRoute: AuthedDashboardReposRoute,
  AuthedDashboardSkillsRoute: AuthedDashboardSkillsRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardPromptsPromptIdRoute: AuthedDashboardPromptsPromptIdRoute,
  AuthedDashboardPromptsNewRoute: AuthedDashboardPromptsNewRoute,
  AuthedDashboardStacksStackIdRoute: AuthedDashboardStacksStackIdRoute,
  AuthedDashboardStacksNewRoute: AuthedDashboardStacksNewRoute,
  AuthedDashboardPromptsIndexRoute: AuthedDashboardPromptsIndexRoute,
  AuthedDashboardStacksIndexRoute: AuthedDashboardStacksIndexRoute,
};

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren
);

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren;
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren;
  AuthedSubmitRoute: typeof AuthedSubmitRoute;
  AuthedSubmitServerRoute: typeof AuthedSubmitServerRoute;
  AuthedSettingsSecretsRoute: typeof AuthedSettingsSecretsRoute;
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  AuthedSubmitRoute: AuthedSubmitRoute,
  AuthedSubmitServerRoute: AuthedSubmitServerRoute,
  AuthedSettingsSecretsRoute: AuthedSettingsSecretsRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
};

const AuthedRouteWithChildren = AuthedRoute._addFileChildren(AuthedRouteChildren);

interface ExploreDocsRouteChildren {
  ExploreDocsLibraryIdRoute: typeof ExploreDocsLibraryIdRoute;
}

const ExploreDocsRouteChildren: ExploreDocsRouteChildren = {
  ExploreDocsLibraryIdRoute: ExploreDocsLibraryIdRoute,
};

const ExploreDocsRouteWithChildren = ExploreDocsRoute._addFileChildren(ExploreDocsRouteChildren);

interface ExploreRouteChildren {
  ExploreDocsRoute: typeof ExploreDocsRouteWithChildren;
  ExploreStatsRoute: typeof ExploreStatsRoute;
  ExploreIndexRoute: typeof ExploreIndexRoute;
  ExploreServersServerIdRoute: typeof ExploreServersServerIdRoute;
  ExploreSkillsSkillIdRoute: typeof ExploreSkillsSkillIdRoute;
  ExploreStacksStackSlugRoute: typeof ExploreStacksStackSlugRoute;
  ExploreServersIndexRoute: typeof ExploreServersIndexRoute;
  ExploreSkillsIndexRoute: typeof ExploreSkillsIndexRoute;
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreDocsRoute: ExploreDocsRouteWithChildren,
  ExploreStatsRoute: ExploreStatsRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ExploreServersServerIdRoute: ExploreServersServerIdRoute,
  ExploreSkillsSkillIdRoute: ExploreSkillsSkillIdRoute,
  ExploreStacksStackSlugRoute: ExploreStacksStackSlugRoute,
  ExploreServersIndexRoute: ExploreServersIndexRoute,
  ExploreSkillsIndexRoute: ExploreSkillsIndexRoute,
};

const ExploreRouteWithChildren = ExploreRoute._addFileChildren(ExploreRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ExploreRoute: ExploreRouteWithChildren,
  PlansRoute: PlansRoute,
  SignInRoute: SignInRoute,
  TerminalRoute: TerminalRoute,
  AuthCliRoute: AuthCliRoute,
  CodeSessionsRoute: CodeSessionsRoute,
  LibrariesLibraryIdRoute: LibrariesLibraryIdRoute,
  CodeIndexRoute: CodeIndexRoute,
  CodeSessionSessionIdRoute: CodeSessionSessionIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
