import type { Database, ApiTokenScope } from "@nexus/db";

// Env type is generated by wrangler types and available globally
// See worker-configuration.d.ts

export interface AuthUser {
  id: string;
  name: string;
  email: string;
  image?: string | null;
  role?: string;
}

export interface AuthSession {
  id: string;
  userId: string;
  expiresAt: Date;
}

export type AuthType = "session" | "token" | "anonymous";

export interface AppContext {
  Bindings: Env;
  Variables: {
    db: Database;
    user?: AuthUser;
    session?: AuthSession;
    authType?: AuthType;
    tokenScopes?: ApiTokenScope[];
    tokenId?: string;
  };
}

// ============================================================================
// MCP Protocol Types
// ============================================================================

export interface MCPRequest {
  jsonrpc: "2.0";
  id: string | number;
  method: string;
  params?: Record<string, unknown>;
}

export interface MCPResponse {
  jsonrpc: "2.0";
  id: string | number;
  result?: unknown;
  error?: MCPError;
}

export interface MCPError {
  code: number;
  message: string;
  data?: unknown;
}

export interface MCPToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: "object";
    properties: Record<string, unknown>;
    required?: string[];
  };
}

/**
 * Response format for token-efficient responses.
 * - full: Complete response with all metadata (default)
 * - compact: Essential data only, minimal formatting
 * - code-only: Only code blocks and essential context
 * - summary: Brief summary with key points
 */
export type ResponseFormat = "full" | "compact" | "code-only" | "summary";

export interface MCPSession {
  createdAt: number;
  lastAccessedAt: number;
  userId?: string;
  requestCount: number;
}

// ============================================================================
// Documentation Types
// ============================================================================

export interface DocChunk {
  id: string;
  libraryId: string;
  title: string | null;
  content: string;
  contentType: "text" | "code" | "mixed";
  sourceFile: string | null;
  sourceUrl: string | null;
  tokenCount: number;
  score?: number;
}

export interface SearchResult {
  chunks: DocChunk[];
  library: {
    id: string;
    name: string;
    version: string | null;
  };
  totalResults: number;
}

export interface LibraryInfo {
  id: string;
  name: string;
  description: string | null;
  sourceType: "github" | "website" | "npm" | "context7";
  sourceUrl: string;
  context7Id: string | null;
  repositoryUrl: string | null;
  homepageUrl: string | null;
  iconUrl: string | null;
  version: string | null;
  categories: string[];
  totalChunks: number;
  totalTokens: number;
  indexStatus: "pending" | "indexing" | "indexed" | "failed";
  lastIndexedAt: string | null;
  isFeatured: boolean;
}

// ============================================================================
// Ingestion Types
// ============================================================================

export interface IngestionJob {
  libraryId: string;
  libraryName?: string;
  sourceUrl: string;
  sourceType: "github" | "website" | "npm" | "context7";
  context7Id?: string;
}

// ============================================================================
// Stack Learning Types
// ============================================================================

export type StackLearningTaskType = "analyze_repo" | "research_package" | "compile_prompt";

export interface StackLearningJob {
  stackId: string;
  userId: string;
  taskType: StackLearningTaskType;
  // For repo analysis
  repoId?: string;
  githubUrl?: string;
  isPrivate?: boolean;
  branch?: string;
  paths?: string[];
  // For package research
  packageId?: string;
  packageName?: string;
  registry?: string;
  // For compilation
  tokenBudget?: "minimal" | "standard" | "comprehensive";
}

export interface ChunkData {
  id: string;
  title: string | null;
  content: string;
  contentType: "text" | "code" | "mixed";
  sourceFile: string | null;
  tokenCount: number;
}

export interface GitHubContent {
  path: string;
  content: string;
}

// ============================================================================
// Memory Types
// ============================================================================

export type MemoryType = "project_context" | "session_summary" | "decision" | "correction";

export type MemoryScope = "global" | "user";

export interface MemoryMetadata {
  id: string;
  scope: MemoryScope;
  type: MemoryType;
  project: string | null;
  userId: string | null;
  title: string;
  tags: string[];
}

export interface MemoryResult {
  memoryId: string;
  title: string;
  type: MemoryType;
  content: string;
  summary: string | null;
  tags: string[];
  project: string | null;
  importance: number;
  relevanceScore?: number;
  createdAt: string;
  updatedAt: string;
}

// ============================================================================
// API Response Types
// ============================================================================

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    limit: number;
    offset: number;
    total: number;
    hasMore: boolean;
  };
}

export interface ApiError {
  error: string;
  code?: string;
  details?: unknown;
}
