import type { Database } from "@nexus/db";

// Env type is generated by wrangler types and available globally
// See worker-configuration.d.ts

export interface AppContext {
  Bindings: Env;
  Variables: {
    db: Database;
  };
}

// ============================================================================
// MCP Protocol Types
// ============================================================================

export interface MCPRequest {
  jsonrpc: "2.0";
  id: string | number;
  method: string;
  params?: Record<string, unknown>;
}

export interface MCPResponse {
  jsonrpc: "2.0";
  id: string | number;
  result?: unknown;
  error?: MCPError;
}

export interface MCPError {
  code: number;
  message: string;
  data?: unknown;
}

export interface MCPToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: "object";
    properties: Record<string, unknown>;
    required?: string[];
  };
}

// ============================================================================
// Documentation Types
// ============================================================================

export interface DocChunk {
  id: string;
  libraryId: string;
  title: string | null;
  content: string;
  contentType: "text" | "code" | "mixed";
  sourceFile: string | null;
  sourceUrl: string | null;
  tokenCount: number;
  score?: number;
}

export interface SearchResult {
  chunks: DocChunk[];
  library: {
    id: string;
    name: string;
    version: string | null;
  };
  totalResults: number;
}

export interface LibraryInfo {
  id: string;
  name: string;
  description: string | null;
  sourceType: "github" | "website" | "npm";
  sourceUrl: string;
  repositoryUrl: string | null;
  homepageUrl: string | null;
  iconUrl: string | null;
  version: string | null;
  categories: string[];
  totalChunks: number;
  totalTokens: number;
  indexStatus: "pending" | "indexing" | "indexed" | "failed";
  lastIndexedAt: string | null;
  isFeatured: boolean;
}

// ============================================================================
// Ingestion Types
// ============================================================================

export interface IngestionJob {
  libraryId: string;
  sourceUrl: string;
  sourceType: "github" | "website" | "npm";
}

export interface ChunkData {
  id: string;
  title: string | null;
  content: string;
  contentType: "text" | "code" | "mixed";
  sourceFile: string | null;
  tokenCount: number;
}

export interface GitHubContent {
  path: string;
  content: string;
}

// ============================================================================
// API Response Types
// ============================================================================

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    limit: number;
    offset: number;
    total: number;
    hasMore: boolean;
  };
}

export interface ApiError {
  error: string;
  code?: string;
  details?: unknown;
}
